---
- name: Ansible Playbook
  hosts: Development
  become: true
  user: ubuntu
  gather_facts : true
  roles:
    - apache
    - php
    - mysql
    
  vars:
   ansible_ssh_private_key_file: /Applications/XAMPP/xamppfiles/htdocs/cicd_learning/krishna.pem