---
- name: Ansible Playbook
  hosts: Development
  become: true
  user: ubuntu
  gather_facts : true
  roles:
    - apache
    - php
    - mysql
    
  vars:
   ansible_ssh_private_key_file: /home/runner/work/cicd/cicd/ansible/krishna.pem